-- OPLIMA.PCORCAVENDAI definition

CREATE TABLE "OPLIMA"."PCORCAVENDAI" 
   (	"NUMORCA" NUMBER(10,0) NOT NULL ENABLE, 
	"DATA" DATE, 
	"CODCLI" NUMBER(9,0) NOT NULL ENABLE, 
	"CODPROD" NUMBER(6,0) NOT NULL ENABLE, 
	"CODUSUR" NUMBER(4,0) NOT NULL ENABLE, 
	"QT" NUMBER(20,6) NOT NULL ENABLE, 
	"PVENDA" NUMBER(19,6) NOT NULL ENABLE, 
	"PTABELA" NUMBER(19,6) NOT NULL ENABLE, 
	"NUMCAR" NUMBER(8,0), 
	"POSICAO" VARCHAR2(2) NOT NULL ENABLE, 
	"ST" NUMBER(18,6) NOT NULL ENABLE, 
	"VLCUSTOFIN" NUMBER(18,6) NOT NULL ENABLE, 
	"VLCUSTOREAL" NUMBER(18,6) NOT NULL ENABLE, 
	"PERCOM" NUMBER(8,4) NOT NULL ENABLE, 
	"PERDESC" NUMBER(18,6) NOT NULL ENABLE, 
	"QTFALTA" NUMBER(20,6), 
	"NUMSEQ" NUMBER(20,0), 
	"TIPOPESO" VARCHAR2(1), 
	"PERCOMTAB" NUMBER(8,4), 
	"PERDESCTAB" NUMBER(8,4), 
	"NUMEROETIQIMPRESSA" NUMBER(1,0), 
	"REFCOR" VARCHAR2(20), 
	"MARGEM" NUMBER(10,2), 
	"PERDESCAUX" NUMBER(5,2), 
	"PVENDABASE" NUMBER(18,6), 
	"CODST" NUMBER(4,0), 
	"IVA" NUMBER(8,4), 
	"ALIQICMS1" NUMBER(8,4), 
	"ALIQICMS2" NUMBER(8,4), 
	"PAUTA" NUMBER(8,4), 
	"PERCBASERED" NUMBER(8,4), 
	"VLDESCCOM" NUMBER(18,6), 
	"PERDESCCOM" NUMBER(12,4), 
	"PERDESCFIN" NUMBER(12,4), 
	"VLBONIFIC" NUMBER(18,6), 
	"PERBONIFIC" NUMBER(12,4), 
	"VLDESCFIN" NUMBER(18,6), 
	"CUSTOFINEST" NUMBER(18,6), 
	"PERFRETECMV" NUMBER(8,4), 
	"VLDESCRODAPE" NUMBER(18,6), 
	"PERCBASEREDST" NUMBER(8,4), 
	"PERCBASEREDSTFONTE" NUMBER(8,4), 
	"COMPLEMENTO" VARCHAR2(40), 
	"PERCISS" NUMBER(8,4), 
	"VLISS" NUMBER(18,6), 
	"PERCIPI" NUMBER(12,4), 
	"VLIPI" NUMBER(18,6), 
	"CODAUXILIAR" NUMBER(20,0), 
	"LOCALIZACAO" VARCHAR2(40), 
	"CODPROMOCAO" VARCHAR2(10), 
	"PRAZOMEDIO" NUMBER(4,0), 
	"VLDESCICMISENCAO" NUMBER(18,6), 
	"VLREPASSE" NUMBER(18,6), 
	"CODFILIALRETIRA" VARCHAR2(2), 
	"PERCVENDA" NUMBER(5,2), 
	"VLDESCPISSUFRAMA" NUMBER(18,6), 
	"PORIGINAL" NUMBER(18,6), 
	"VLCUSTOCONT" NUMBER(18,6), 
	"VLCUSTOREP" NUMBER(18,6), 
	"PERDESCFLEX" NUMBER(18,6), 
	"VLDESCFLEX" NUMBER(18,6), 
	"PERREDCOMISS" NUMBER(18,6), 
	"VLREDCOMISS" NUMBER(18,6), 
	"TIPODESCAPLICADO" VARCHAR2(2), 
	"PBASERCA" NUMBER(18,6), 
	"PESOBRUTO" NUMBER(7,3), 
	"VLVERBACMV" NUMBER(18,6), 
	"NUMVERBAREBCMV" NUMBER(6,0), 
	"PERCOMSUP" NUMBER(8,4), 
	"PERREDCOMISSSUP" NUMBER(18,6), 
	"VLREDCOMISSSUP" NUMBER(18,6), 
	"QTCX" NUMBER(14,6), 
	"QTPECAS" NUMBER(14,6), 
	"PERDESCCUSTO" NUMBER(8,4), 
	"TXVENDA" NUMBER(8,6), 
	"CODICMTAB" NUMBER(8,4), 
	"PERDESCISENTOICMS" NUMBER(4,2), 
	"PERCOMPROF" NUMBER(6,2), 
	"ESCANIADO" NUMBER(4,0), 
	"NUMSEQFORMULA" NUMBER(20,0), 
	"CODMAQUINA" NUMBER(4,0), 
	"CHAVEPRINCIPAL" VARCHAR2(40), 
	"CODFORMULA" VARCHAR2(20), 
	"CODPRODTINTA" VARCHAR2(40), 
	"CODBASE" VARCHAR2(40), 
	"VOLUMEDESEJADO" NUMBER(12,4), 
	"SIGLAQUALIDADE" VARCHAR2(10), 
	"ALTERNATIVO" VARCHAR2(10), 
	"PVENDA1" NUMBER(18,6), 
	"PERCAGREGADORST" NUMBER(8,4), 
	"QTENTREGUE" NUMBER(16,3), 
	"QTENTREGUEAUX" NUMBER(16,3), 
	"QTIMEDIATA" NUMBER(16,3), 
	"QTPOSTERIOR" NUMBER(16,3), 
	"QTENTREGAR" NUMBER(16,3), 
	"QTRETIRA1" NUMBER(16,3), 
	"QTRETIRA2" NUMBER(16,3), 
	"QTRETIRA3" NUMBER(16,3), 
	"PRODDESCRICAOCONTRATO" VARCHAR2(300), 
	"GERAGNRE_CNPJCLIENTE" VARCHAR2(1), 
	"VLDIFALIQUOTAS" NUMBER(18,6), 
	"BASEDIFALIQUOTAS" NUMBER(18,6), 
	"PERCDIFALIQUOTAS" NUMBER(8,4), 
	"TIPOENTREGA" VARCHAR2(2), 
	"PVENDAANTERIOR" NUMBER(18,6), 
	"PERDESCPOLITICA" NUMBER(8,2), 
	"VLDESCCUSTOCMV" NUMBER(12,4), 
	"VLDESCSUFRAMA" NUMBER(18,6), 
	"STCLIENTEGNRE" NUMBER(18,6), 
	"BRINDE" VARCHAR2(1), 
	"BASEICST" NUMBER(18,6), 
	"LETRACOMISS" VARCHAR2(2), 
	"EANCODPROD" NUMBER(14,0), 
	"VLVERBACMVCLI" NUMBER(18,6), 
	"EXPORTADO" VARCHAR2(1), 
	"DTEXPORTACAO" DATE, 
	"POLITICAPRIORITARIA" VARCHAR2(1), 
	"QTUNITEMB" NUMBER(18,6), 
	"TRUNCARITEM" VARCHAR2(1), 
	"PERCOM2" NUMBER(8,4), 
	"PERCOM3" NUMBER(8,4), 
	"PERCOM4" NUMBER(8,4), 
	"TIPOMERC" VARCHAR2(2), 
	"NUMSEQCESTA" NUMBER(20,0), 
	"CODDESCONTO" NUMBER(8,0), 
	"FATORPRECO" NUMBER(20,8), 
	"PVENDAATAC" NUMBER(12,3), 
	"QTMINIMAATACADO" NUMBER(18,6), 
	"PERCDESCQUANT" NUMBER(6,2), 
	"PERCDESC_POLITICA" NUMBER(10,4), 
	"PRECOFIXO" NUMBER(18,6), 
	"CODCOMBO" NUMBER(6,0), 
	"VLREDPVENDASIMPLESNA" NUMBER(18,6), 
	"VLREDCMVSIMPLESNAC" NUMBER(18,6), 
	"CODOFERTAORIG" NUMBER(6,0), 
	"STPBASERCA" NUMBER(18,6), 
	"STPTABELA" NUMBER(18,6), 
	"GRUPOFATURAMENTO" VARCHAR2(1), 
	"DTENTREGA" DATE, 
	"RP_IMEDIATA" VARCHAR2(1), 
	"NUMSEQITEMCONTRATO" NUMBER(6,0), 
	"NUMLISTA" NUMBER(6,0), 
	"PERDESCNEGOCIADO" NUMBER(18,6), 
	"FORMANEGOCIACAO" VARCHAR2(1), 
	"PERDESCAVISTA" NUMBER(18,6), 
	"NEGOCIACAOPOSTERIOR" VARCHAR2(1), 
	"CODEMITENTEITEMPEDIDO" NUMBER(8,0), 
	"CODPRECOFIXO" NUMBER(18,6), 
	"VLACRESFRETEKG" NUMBER(12,6), 
	"STATUSSUCATA" NUMBER(1,0), 
	"NUMORCAORIG" NUMBER(10,0), 
	"NUMFICHAORIG" NUMBER(10,0), 
	"MATRICULA" NUMBER(8,0), 
	"DTULTALTER" DATE DEFAULT SYSDATE, 
	"NUMLOTE" VARCHAR2(15), 
	"OBSERVACAO" VARCHAR2(300), 
	"BAIXADO" VARCHAR2(1) DEFAULT 'N', 
	"UNIDADE" VARCHAR2(2), 
	"PERDESCPAUTA" NUMBER(18,6), 
	"ORIGEMST" VARCHAR2(1), 
	"AMBIENTE" VARCHAR2(50), 
	"TAXACASOMOEDAREAL" NUMBER(12,6), 
	"CODMOEDAESTRAGEIRA" NUMBER(6,0), 
	"VLRMOEDAESTRAGEIRA" NUMBER(18,6), 
	"QTDIASENTREGAITEM" NUMBER(4,0), 
	"NUMITEMORCA" NUMBER(6,0), 
	"VLACRESCCOMPLEMENTO" NUMBER(18,6), 
	"IMPRIMERESTAURANTE" VARCHAR2(1), 
	"IMPRESSORESTAURANTE" VARCHAR2(1), 
	"CODIMP" NUMBER(10,0), 
	"NUMSEQIMPRESSAO" NUMBER(6,0), 
	"BONIFIC" VARCHAR2(1), 
	"CODINDICEMULTIPLICADOR" NUMBER(6,0), 
	"OBS1" VARCHAR2(400), 
	"OBS2" VARCHAR2(400), 
	"PBONIFIC" NUMBER(18,6), 
	"PERCREDALIQIPI" NUMBER(18,6), 
	"PVENDALIQ" NUMBER(18,6), 
	"ROTINALANC" VARCHAR2(48), 
	"CODPRODCESTA" NUMBER(6,0), 
	"VLTOTSERVICO" NUMBER(22,6), 
	"PRODUZIR_TINTA" VARCHAR2(1), 
	"PROMOCAO" VARCHAR2(1), 
	"VLBASEPARTDEST" NUMBER(18,6), 
	"ALIQFCP" NUMBER(18,6), 
	"ALIQINTERNADEST" NUMBER(18,6), 
	"VLFCPPART" NUMBER(18,6), 
	"VLICMSPARTDEST" NUMBER(18,6), 
	"VLICMSPART" NUMBER(18,6), 
	"PERCPROVPART" NUMBER(5,2), 
	"VLICMSDIFALIQPART" NUMBER(22,6), 
	"PERCBASEREDPART" NUMBER(5,2), 
	"VLICMSPARTREM" NUMBER(18,6), 
	"ALIQINTERORIGPART" NUMBER(18,6), 
	"VLIPIPTABELA" NUMBER(18,6), 
	"VLIPIPBASERCA" NUMBER(18,6), 
	"VLICMSPARTPTABELA" NUMBER(18,6), 
	"VLICMSPARTPBASERCA" NUMBER(18,6), 
	"NUMITEMPED" NUMBER(10,0), 
	"CODDESCONTOSIMULADOR" NUMBER(8,0), 
	"CODMOTIVONAOATENDPROD" NUMBER(3,0), 
	"PERCDESCPIS" NUMBER(12,4), 
	"VLDESCREDUCAOPIS" NUMBER(24,6), 
	"PERCDESCCOFINS" NUMBER(12,4), 
	"VLDESCREDUCAOCOFINS" NUMBER(24,6), 
	"CODFIGVENDATRIANGULAR" NUMBER(4,0), 
	"CODFISCAL" NUMBER(8,0) DEFAULT '', 
	"SITTRIBUT" VARCHAR2(3) DEFAULT '', 
	"VERSAOSERVICOPARTILHA" VARCHAR2(10) DEFAULT '', 
	"DTENTREGAMESA" DATE, 
	"CODFUNCENTREGAMESA" NUMBER(8,0), 
	"PRODIMPORTADOPEPS" VARCHAR2(1), 
	"NUMTRANSENTPEPS" NUMBER(10,0), 
	"PTABELAFABRICAZFM" NUMBER(18,6), 
	"SERVIMP" NUMBER(10,0), 
	"ORIGMERCTRIB" VARCHAR2(1), 
	"CODIMPSERVIMP" NUMBER(10,0), 
	"DTENVIOSERVCARGA" DATE, 
	"DESCONSIDERARDESCATACADO" VARCHAR2(1), 
	"DESCRICAOPAF" VARCHAR2(200), 
	"MD5PAF" VARCHAR2(200), 
	"VLBASEFCPICMS" NUMBER(18,6), 
	"VLBASEFCPST" NUMBER(18,6), 
	"VLBCFCPSTRET" NUMBER(18,6), 
	"PERFCPSTRET" NUMBER(12,4), 
	"VLFCPSTRET" NUMBER(18,6), 
	"PERFCPSN" NUMBER(12,4), 
	"VLCREDFCPICMSSN" NUMBER(18,6), 
	"VLFECP" NUMBER(18,6), 
	"VLACRESCIMOFUNCEP" NUMBER(18,6), 
	"PERACRESCIMOFUNCEP" NUMBER(12,4), 
	"ALIQICMSFECP" NUMBER(12,4), 
	"BAIXAQTFRENTELOJA" VARCHAR2(1), 
	"UTILIZOUMOTORCALCULO" VARCHAR2(1), 
	"CODECF" VARCHAR2(6), 
	"NUMVERBACAMPANHA" NUMBER(8,0), 
	"PERCCUSTFORNEC" NUMBER(12,4), 
	"VLCUSTFORNEC" NUMBER(18,6), 
	"VLOUTRASDESP" NUMBER(18,6), 
	"VLACRESCRODAPE" NUMBER(18,6), 
	"NUMCCF" NUMBER(8,0), 
	"CODIGOINTEGRACAOWMS" VARCHAR2(15), 
	"NUMLOTEPROMOCAOMED" VARCHAR2(20), 
	"CODDEPOSITO" NUMBER(10,0), 
	"CODPROMOCAOMED" NUMBER(9,0), 
	"NUMPEDCLI" VARCHAR2(15), 
	"VLDESCCMVPROMOCAOMED" NUMBER(18,6), 
	"CODCONTRATO" NUMBER(6,0), 
	 CONSTRAINT "PCORCAVENDAI_PK" PRIMARY KEY ("NUMORCA", "CODPROD", "NUMSEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DADOS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 327680 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DADOS" ;

CREATE OR REPLACE TRIGGER "OPLIMA"."TRG_LOG_PVENDAORCAMENTO" 
 AFTER
   INSERT OR UPDATE OF PVENDA
 ON PCORCAVENDAI
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
declare
  vsmaquina varchar2(80);
  vsusuario varchar2(80);
  vsprograma varchar2(80);
begin

   vsmaquina := SYS_CONTEXT('USERENV','TERMINAL');
   vsusuario := SYS_CONTEXT('USERENV','OS_USER');
   vsprograma := F_OBTERNOMEAPLICACAO;

   IF (inserting) THEN
     IF nvl(:new.pvenda,0) <> nvl(:new.ptabela,0) THEN
       insert into LOGPVENDAORCAMENTO
        (codprod,
         pvenda_ant,
         pvenda,
         data_ATUALIZACAO,
         programa,
         maquina,
         usuario)
         values
           (:new.codprod,
            :new.ptabela,
            :new.pvenda,
            null,
            vsprograma,
            vsmaquina,
            vsusuario);
      END IF;
     END IF;

   IF (updating) THEN
     IF nvl(:old.pvenda,0) <> nvl(:old.ptabela,0) THEN
       insert into LOGPVENDAORCAMENTO
        (codprod,
         pvenda_ant,
         pvenda,
         data_ATUALIZACAO,
         programa,
         maquina,
         usuario)
         values
           (:old.codprod,
            :old.ptabela,
            :old.pvenda,
            sysdate,
            vsprograma,
            vsmaquina,
            vsusuario);
    END IF;
   END IF;


end TRG_LOG_PVENDAORCAMENTO;
/
ALTER TRIGGER "OPLIMA"."TRG_LOG_PVENDAORCAMENTO" ENABLE;
  CREATE OR REPLACE TRIGGER "OPLIMA"."TRG_MD5PAF_PCORCAVENDAI" 
  BEFORE UPDATE OR INSERT OR DELETE ON PCORCAVENDAI
  REFERENCING OLD AS OLD NEW AS NEW
  FOR EACH ROW
BEGIN
  if (F_LIMPA_MD5PAF = 'S') then
    if ( UPDATING) then
      :NEW.MD5PAF := NULL;
	  end if;

    if ( INSERTING or DELETING ) then
	    UPDATE PCTABELASMD5PAF set MD5PAF = NULL WHERE TABELA = 'PCORCAVENDAI';
	  end if;
  end if;

END TRG_MD5PAF_PCORCAVENDAI;
/
ALTER TRIGGER "OPLIMA"."TRG_MD5PAF_PCORCAVENDAI" ENABLE;

CREATE UNIQUE INDEX "OPLIMA"."PCORCAVENDAI_PK" ON "OPLIMA"."PCORCAVENDAI" ("NUMORCA", "CODPROD", "NUMSEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DADOS" ;

COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.QT IS 'Quantidade do item no orçamento..';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.QTFALTA IS 'Quantidade da falta do item no orçamento.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERCVENDA IS 'Indica o percentual negociado na venda.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.QTCX IS 'Quantidade de caixas.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.QTPECAS IS 'Quantidade de peças.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PVENDA1 IS 'Valor do preço a vista, para realização de cálculo de comissão sobre preço a vista. ';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.QTIMEDIATA IS 'Quantidade de Entrega Imediata.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.QTPOSTERIOR IS 'Quantidade de Entrega Posterior.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.QTENTREGAR IS 'Quantidade a ser Entregue.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.QTRETIRA1 IS 'Quantidade a ser retirada na filial número 1.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.QTRETIRA2 IS 'Quantidade a ser retirada na filial número 2.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.QTRETIRA3 IS 'Quantidade a ser retirada na filial número 3.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PRODDESCRICAOCONTRATO IS 'Indica a especificação do Contrato. ';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.GERAGNRE_CNPJCLIENTE IS 'Campo para definir se a GNRE será paga pelo cliente. ';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLDIFALIQUOTAS IS 'Valor da diferença de aliquotas.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.BASEDIFALIQUOTAS IS 'Base da diferença entre alíquotas.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERCDIFALIQUOTAS IS 'Percentual de diferença de tributação.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.TIPOENTREGA IS 'Indica o tipo de entrega do Produto. (RP-Retira posterior/EN-Entrega Normal. ';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PVENDAANTERIOR IS 'Indica o preço de venda anterior. ';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERDESCPOLITICA IS 'Indica o percentual de desconto política. ';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLDESCCUSTOCMV IS 'Valor desconto custo CMV. ';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLDESCSUFRAMA IS 'Valor desconto suframa. ';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.STCLIENTEGNRE IS 'Valor ST cliente GNRE. ';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.BRINDE IS 'Item de brinde. ';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.BASEICST IS 'Base de cálculo ST. ';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.LETRACOMISS IS 'Letra de comissão por lucratividade. ';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.EANCODPROD IS 'Código EAN item do contrato. ';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLVERBACMVCLI IS 'Valor verba CMV do cliente. ';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.EXPORTADO IS 'STATUS DO REGISTRO, INDICA SE O REGISTRO FOI EXPORTADO';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.DTEXPORTACAO IS 'Data de exportação do orçamento';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.POLITICAPRIORITARIA IS 'Indica que a política de desconto é prioritária.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.QTUNITEMB IS 'Indica a quantidade uitaria da embalagem.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.TRUNCARITEM IS 'Indica se trunca o varlor total do item.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERCOM2 IS 'Indica a comissão do primeiro profissional.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERCOM3 IS 'Indica a comissão do segundo profissional.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERCOM4 IS 'Indica a comissão do terceiro profissional.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.TIPOMERC IS 'Tipo de Mercadoria.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.NUMSEQCESTA IS 'Número de sequência da cesta básica.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODDESCONTO IS 'Código da política de desconto.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.FATORPRECO IS 'Índice que se aplica ao preço de venda.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PVENDAATAC IS 'Preço de Venda Atacado.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.QTMINIMAATACADO IS 'Quantidade Mínima de Atacado.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERCDESCQUANT IS 'Percentual de Desconto por Quantidade.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERCDESC_POLITICA IS 'Percentual por Política de Desconto.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PRECOFIXO IS 'Preço Fixo.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODCOMBO IS 'Código da política de combo.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLREDPVENDASIMPLESNA IS 'Valor de redução no preço de venda para cliente Simples Nacional.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLREDCMVSIMPLESNAC IS 'Valor de redução no CMV para cliente Simples Nacional.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODOFERTAORIG IS 'Codigo da oferta';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.STPBASERCA IS 'Valor de ST relativo ao preço base RCA';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.STPTABELA IS 'Valor de ST relativo ao preço de tabela';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.GRUPOFATURAMENTO IS 'Grupo Faturamento';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.DTENTREGA IS 'Data de entrega do item';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.RP_IMEDIATA IS 'Retira posterior';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.NUMSEQITEMCONTRATO IS 'Número da Sequência do Item no Contrato';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.NUMLISTA IS 'Número da Lista de Presente';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERDESCNEGOCIADO IS 'Percentudal de desconto negociado.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.FORMANEGOCIACAO IS 'Forma de negociação.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERDESCAVISTA IS 'Percentual de desconta à vista.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.NEGOCIACAOPOSTERIOR IS 'Negociação Posterior.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODEMITENTEITEMPEDIDO IS 'Código emite item pedido.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODPRECOFIXO IS 'Código preço fixo.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLACRESFRETEKG IS 'Valor de acréscimo Frete (kG).';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.STATUSSUCATA IS 'Status Sucata.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.NUMORCAORIG IS 'Número orçamento de origem.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.NUMFICHAORIG IS 'Número da ficha de origem.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.MATRICULA IS 'Matrícula.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.DTULTALTER IS 'Data última alteração.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.NUMLOTE IS 'Número do lote.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.OBSERVACAO IS 'Observação de Item da Ficha.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.BAIXADO IS 'Estado do orçamento como baixado ou não.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.UNIDADE IS 'Unidade da fórmula de tinta';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERDESCPAUTA IS 'Percentual de desconto utilizado para produtos com pauta.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.ORIGEMST IS 'Origem do cálculo de ST';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.AMBIENTE IS 'Nome do Ambiente';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.TAXACASOMOEDAREAL IS 'Taxa caso a moeda escolhida seja o real.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODMOEDAESTRAGEIRA IS 'Guarda código da moeda estrageira no momento da venda';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLRMOEDAESTRAGEIRA IS 'Guarda valor da conversão do real para moeda extrangeira';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.QTDIASENTREGAITEM IS 'Qtde de dias para entregar o produto sem estoque';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.NUMITEMORCA IS 'Número item orçamento cliente.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLACRESCCOMPLEMENTO IS 'Valor de acréscimo do complemento.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.IMPRIMERESTAURANTE IS 'Embalagem permite impressão restaurante';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.IMPRESSORESTAURANTE IS 'Status de impressão do item';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODIMP IS 'Código da Impressora';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.NUMSEQIMPRESSAO IS 'Sequência de impressão';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.BONIFIC IS 'Identificação do item bonificado';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODINDICEMULTIPLICADOR IS 'código indice multiplicador de serviço';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.OBS1 IS 'Observação 1';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.OBS2 IS 'Observação 2';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PBONIFIC IS 'Valor do item bonificado';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERCREDALIQIPI IS '% de Redução da Alíquota de IPI';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PVENDALIQ IS 'preço líquido';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.ROTINALANC IS 'Última rotina que alterou a tabela';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODPRODCESTA IS 'Código do produto cesta Kit Aberto';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLTOTSERVICO IS 'VALOR TOTAL DO SERVIÇO DO PRODUTO NO ORÇAMENTO';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PRODUZIR_TINTA IS 'Produzir Tinta Manipulada';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PROMOCAO IS 'Promoção';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLBASEPARTDEST IS 'Valor da base de cálculo na UF de destino';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.ALIQFCP IS 'Aliquota de FCP(Fundo de combate à pobreza)';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.ALIQINTERNADEST IS 'Aliquota de ]ICMS interna na UF de destino';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLFCPPART IS 'Valor do FUNCEP';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLICMSPARTDEST IS 'Valor do ICMS interestadual para a UF destino';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLICMSPART IS 'Valor de ICMS de partilha(valor que deverá ser utilizado para acrescer o valor do produto';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERCPROVPART IS 'Percentual provisório de partilha de ICMS';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLICMSDIFALIQPART IS 'Valor de ICMS do diferencial de aliquota da partilha de ICMS';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERCBASEREDPART IS 'Redução aplicada na base de Partilha no orçamento';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLICMSPARTREM IS 'Valor do ICMS de partilha para UF remetente';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.ALIQINTERORIGPART IS 'Aliquota de  ICMS da UF de origem';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLIPIPTABELA IS 'Valor de IPI relativo ao preço de tabela';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLIPIPBASERCA IS 'Valor de IPI relativo ao preço base RCA';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLICMSPARTPTABELA IS 'Valor ICMS Partilha relativo ao preço de tabela';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLICMSPARTPBASERCA IS 'Valor ICMS Partilha relativo ao preço base RCA';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.NUMITEMPED IS 'Número do Item no XML da NF';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODDESCONTOSIMULADOR IS 'Indica o código do desconto de simulador no item';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODMOTIVONAOATENDPROD IS 'CÓDIGO DO MOTIVO DO NÃO ATENDIMENTO DO ITEM DO ORÇAMENTO';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERCDESCPIS IS 'Indica o % de pis';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLDESCREDUCAOPIS IS 'indica o valor de desconto de PIS aplicado na venda';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERCDESCCOFINS IS 'Indica o % de COFINS';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLDESCREDUCAOCOFINS IS 'Indica o valor de desconto de COFINS aplicado na venda';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODFIGVENDATRIANGULAR IS 'Define o código da figura tributaria para venda triangular';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODFISCAL IS 'Define o CFOP do item no orçamento';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.SITTRIBUT IS 'Define o CST do item no orçamento';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VERSAOSERVICOPARTILHA IS 'Versão do servido de ICMS Partilha';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.DTENTREGAMESA IS 'Data de entrega da mesa';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODFUNCENTREGAMESA IS 'funcionário de entrega da mesa';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PRODIMPORTADOPEPS IS 'Produto Importado PEPS';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.NUMTRANSENTPEPS IS 'Transação de Entrada PEPS';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.SERVIMP IS 'Código do Servidor de impressão';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.ORIGMERCTRIB IS 'Código de origem da mercadoria para geração da situação tributária';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODIMPSERVIMP IS 'Código do Servidor de impressão';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.DTENVIOSERVCARGA IS 'Data de envio para o servidor de carga';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.DESCONSIDERARDESCATACADO IS 'Desconsiderar item no calculo de atacado.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.DESCRICAOPAF IS 'Descrição de impressão Cupom';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.MD5PAF IS 'Assinatura MD5 do registro do PAF';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLBASEFCPICMS IS 'Valor da base de calculo do Fundo de Combate a Pobreza';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLBASEFCPST IS 'Valor de base de calculo do Fundo de Combate a Pobreza ST';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLBCFCPSTRET IS 'Valor da base de calculo do FCP retido anteriormente por ST';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERFCPSTRET IS 'Percentual do FCP retido anteriormente por Substituição Tributaria';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLFCPSTRET IS 'Valor do FCP retido por Substituição Tributária';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERFCPSN IS 'Aliquota aplicável de cálculo do crédito(SIMPLES NACIONAL)';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLCREDFCPICMSSN IS 'Valor crédito do ICMS que pode ser aproveitado nos termos do art. 23 da LC 123 (SIMPLES NACIONAL)';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLFECP IS 'Valor Fecp.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLACRESCIMOFUNCEP IS 'Valor Acrescimo FUNCEP';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERACRESCIMOFUNCEP IS 'Percentual Acrescimo FUNCEP';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.ALIQICMSFECP IS 'Alíquota de ICMS Fecp.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.BAIXAQTFRENTELOJA IS 'Identifica baixa de estoque na loja ou no deposito';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.UTILIZOUMOTORCALCULO IS 'Indica se utilizou motor de calculo para calcular o preço de venda';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODECF IS 'Aliquotas da ECF';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.NUMVERBACAMPANHA IS 'Nr. da verba atribuída a campanha.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.PERCCUSTFORNEC IS 'Percentual custeado pelo fornecedor.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLCUSTFORNEC IS 'Valor unitário custeado pelo fornecedor.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLOUTRASDESP IS 'Acréscimos no item';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLACRESCRODAPE IS 'Acréscimos no rodapé';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODIGOINTEGRACAOWMS IS 'Lote da Promoção para indução do lote';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.NUMLOTEPROMOCAOMED IS 'Código da integração do WMS';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODDEPOSITO IS 'Código do depósito informado para o orçamento durante a venda.';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODPROMOCAOMED IS 'Código da Promoção de Medicamentos';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.NUMPEDCLI IS 'Número do pedido do cliente';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.VLDESCCMVPROMOCAOMED IS 'Vl. Verba Fornec. Promocao';
COMMENT ON COLUMN OPLIMA.PCORCAVENDAI.CODCONTRATO IS 'Código do contrato utilizado';