-- rot-111 rotina 111 supervisor
SELECT NVL(CODSUPERVISOR, 0) CODSUPERVISOR, 
       NVL(SUM(QTPOSITIVACAOPREVISTOS), 0) QTPOSITIVACAOPREVISTOS, 
       NVL(SUM(QTPOSITIVACAOFATURADOS), 0) QTPOSITIVACAOFATURADOS, 
       NVL(SUM(QTPOSITIVACAOPREVFAT), 0) QTPOSITIVACAOPREVFAT, 
       NVL(SUM(VLPEDIDO), 0) VLPEDIDO, 
       NVL(SUM(VLFATURAMENTO), 0) VLFATURAMENTO, 
       NVL(SUM(VLPEDIDOFATURADO), 0) VLPEDIDOFATURADO, 
       NVL(SUM(VLVENDA), 0) VLVENDA, 
       NVL(SUM(VLVENDALIQUIDA), 0) VLVENDALIQUIDA, 
       NVL(SUM(VLCMV), 0) VLCMV, 
       NVL(SUM(VLLUCRO), 0) VLLUCRO, 
       NVL(SUM(PERCLUCRO), 0) PERCLUCRO 
  FROM ( 
SELECT DADOS.CODSUPERVISOR, 
       count(distinct DADOS.CODCLIPREVISTOS) QTPOSITIVACAOPREVISTOS, 
       :QTPOSITIVACAOFATURADOS QTPOSITIVACAOFATURADOS, 
       count(distinct DADOS.CODCLIPREVISTOS) + :QTPOSITIVACAOFATURADOS QTPOSITIVACAOPREVFAT, 
       SUM(DADOS.VLPEDIDO) VLPEDIDO, 
       SUM(DADOS.VLFATURAMENTO) VLFATURAMENTO, 
       (SUM(DADOS.VLPEDIDO) + SUM(DADOS.VLFATURAMENTO)) VLPEDIDOFATURADO, 
       SUM(DADOS.VLVENDA) VLVENDA, 
       (SUM(DADOS.VLVENDA) - SUM(DADOS.VLDEVOLUCAO)) VLVENDALIQUIDA, 
       (SUM(DADOS.VLCMV) - SUM(DADOS.VLCMVDEVOLUCAO)) VLCMV, 
       ((SUM(DADOS.VLVENDA) - SUM(DADOS.VLDEVOLUCAO)) - (SUM(DADOS.VLCMV) - SUM(DADOS.VLCMVDEVOLUCAO))) VLLUCRO, 
      (CASE 
        WHEN SUM(DADOS.VLVENDA) <> 0 THEN 
          (((SUM(DADOS.VLVENDA) - SUM(DADOS.VLDEVOLUCAO)) - 
           (SUM(DADOS.VLCMV) - SUM(DADOS.VLCMVDEVOLUCAO))) / 
           SUM(DADOS.VLVENDA)) * 100 
        ELSE 
          0 
      END) PERCLUCRO 
 FROM ( 
SELECT 1 CODIGO, 
       PCPEDC.CODCLI CODCLIPREVISTOS, 
       0 CODCLIFATURADOS, 
       PCPEDC.CODCLI, 
       PCPEDC.NUMPED, 
       PCPEDC.DATA, 
       PCPEDC.POSICAO, 
       PCUSUARI.CODSUPERVISOR, 
       PCUSUARI.CODUSUR, 
       PCUSUARI.NOME NOMERCA, 
       PCSUPERV.CODGERENTE, 
       PCPRODUT.CODFORNEC, 
       PCPRODUT.CODMARCA, 
       PCPRODUT.CODLINHAPROD, 
       NVL(PCFORNEC.CODFORNECPRINC, PCFORNEC.CODFORNEC) CODFORNECPRINC, 
       PCPRODUT.CODPROD, 
       SUM((PCPEDI.PVENDA - 
            DECODE(:DEDUZ_ST, 'S', PCPEDI.ST, 0) - 
            DECODE(:DEDUZ_IPI, 'S', PCPEDI.VLIPI, 0)) * 
           PCPEDI.QT) VLPEDIDO, 
       0 VLFATURAMENTO, 
       SUM((PCPEDI.PVENDA - 
            DECODE(:DEDUZ_ST, 'S', PCPEDI.ST, 0) - 
            DECODE(:DEDUZ_IPI, 'S', PCPEDI.VLIPI, 0)) * 
           PCPEDI.QT) VLVENDA, 
       SUM((PCPEDI.VLCUSTOFIN - 
            DECODE(:DEDUZ_ST, 'S', PCPEDI.ST, 0) - 
            DECODE(:DEDUZ_IPI, 'S', PCPEDI.VLIPI, 0)) * 
           PCPEDI.QT) VLCMV, 
       0 VLDEVOLUCAO, 
       0 VLCMVDEVOLUCAO
  FROM PCPEDC, 
       PCPEDI, 
       PCUSUARI, 
       PCSUPERV, 
       PCGERENTE, 
       PCCLIENT, 
       PCPRODUT, 
       PCFORNEC, 
       PCATIVI 
 WHERE PCPEDC.NUMPED      = PCPEDI.NUMPED
   AND PCPEDC.CODUSUR     = PCUSUARI.CODUSUR
   AND PCPEDC.CODCLI      = PCCLIENT.CODCLI
   AND PCPEDI.CODPROD     = PCPRODUT.CODPROD
   AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
   AND PCCLIENT.CODATV1   = PCATIVI.CODATIV
   AND PCPEDC.CONDVENDA NOT IN ( 4, 8 ) 
   AND PCSUPERV.CODGERENTE = PCGERENTE.CODGERENTE
   AND PCPEDC.DTENTREGA BETWEEN TO_DATE(:DTINICIOPEDIDO, 'DD/MM/YYYY') AND TO_DATE(:DTFIMPEDIDO, 'DD/MM/YYYY')
   AND PCPEDC.POSICAO NOT IN ('F', 'C') 
AND (PCPEDC.CODFILIAL IN ( '75' )) 
   AND PCPEDC.CONDVENDA NOT IN ( 10 ) 
   AND PCUSUARI.CODSUPERVISOR = PCSUPERV.CODSUPERVISOR
 GROUP BY PCPEDC.CODCLI, 
          PCPEDC.NUMPED, 
          PCPEDC.DATA, 
          PCPEDC.POSICAO, 
          PCUSUARI.CODSUPERVISOR, 
          PCUSUARI.CODUSUR, 
          PCUSUARI.NOME, 
          PCSUPERV.CODGERENTE, 
          PCPRODUT.CODFORNEC, 
          PCPRODUT.CODMARCA, 
          PCPRODUT.CODLINHAPROD, 
          NVL(PCFORNEC.CODFORNECPRINC, PCFORNEC.CODFORNEC), 
          PCPRODUT.CODPROD
) DADOS
 GROUP BY DADOS.CODSUPERVISOR
          ) DADOS 
 GROUP BY DADOS.CODSUPERVISOR
